/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as NamelogyRouteImport } from './routes/namelogy'
import { Route as NumerologyRouteImport } from './routes/numerology'
import { Route as ServicesRouteImport } from './routes/services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const NamelogyRoute = NamelogyRouteImport.update({
  id: '/namelogy',
  path: '/namelogy',
  getParentRoute: () => rootRouteImport,
} as any)
const NumerologyRoute = NumerologyRouteImport.update({
  id: '/numerology',
  path: '/numerology',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/namelogy': typeof NamelogyRoute
  '/numerology': typeof NumerologyRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/namelogy': typeof NamelogyRoute
  '/numerology': typeof NumerologyRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/namelogy': typeof NamelogyRoute
  '/numerology': typeof NumerologyRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/namelogy' | '/numerology' | '/services'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/namelogy' | '/numerology' | '/services'
  id: '__root__' | '/' | '/about' | '/namelogy' | '/numerology' | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  NamelogyRoute: typeof NamelogyRoute
  NumerologyRoute: typeof NumerologyRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namelogy': {
      id: '/namelogy'
      path: '/namelogy'
      fullPath: '/namelogy'
      preLoaderRoute: typeof NamelogyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numerology': {
      id: '/numerology'
      path: '/numerology'
      fullPath: '/numerology'
      preLoaderRoute: typeof NumerologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  NamelogyRoute: NamelogyRoute,
  NumerologyRoute: NumerologyRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
